name: LuvstarPlugin
main: me.pilkeysek.LuvstarPlugin
version: 0.1
commands:
  lock:
    description: Lock a chest
    usage: \"/lock\" while looking at the chest
  unlock:
    description: Unlock a chest
    usage: \"/unlock\"" while looking at the chest